INFO:     Started server process [73696]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started server process [188305]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started server process [188948]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
[2022-09-19 14:29:59 +0700] [193426] [INFO] Starting gunicorn 20.1.0
[2022-09-19 14:29:59 +0700] [193426] [INFO] Listening at: http://0.0.0.0:8000 (193426)
[2022-09-19 14:29:59 +0700] [193426] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-09-19 14:29:59 +0700] [193428] [INFO] Booting worker with pid: 193428
[2022-09-19 14:29:59 +0700] [193429] [INFO] Booting worker with pid: 193429
[2022-09-19 14:29:59 +0700] [193433] [INFO] Booting worker with pid: 193433
[2022-09-19 14:29:59 +0700] [193437] [INFO] Booting worker with pid: 193437
[2022-09-19 14:30:00 +0700] [193429] [INFO] Started server process [193429]
[2022-09-19 14:30:00 +0700] [193429] [INFO] Waiting for application startup.
[2022-09-19 14:30:00 +0700] [193429] [INFO] Application startup complete.
[2022-09-19 14:30:00 +0700] [193428] [INFO] Started server process [193428]
[2022-09-19 14:30:00 +0700] [193428] [INFO] Waiting for application startup.
[2022-09-19 14:30:00 +0700] [193428] [INFO] Application startup complete.
[2022-09-19 14:30:01 +0700] [193433] [INFO] Started server process [193433]
[2022-09-19 14:30:01 +0700] [193433] [INFO] Waiting for application startup.
[2022-09-19 14:30:01 +0700] [193433] [INFO] Application startup complete.
[2022-09-19 14:30:01 +0700] [193437] [INFO] Started server process [193437]
[2022-09-19 14:30:01 +0700] [193437] [INFO] Waiting for application startup.
[2022-09-19 14:30:01 +0700] [193437] [INFO] Application startup complete.
[2022-10-18 17:50:38 +0700] [1368076] [INFO] Starting gunicorn 20.1.0
[2022-10-18 17:50:38 +0700] [1368076] [INFO] Listening at: http://10.242.184.93:8000 (1368076)
[2022-10-18 17:50:38 +0700] [1368076] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-10-18 17:50:38 +0700] [1368078] [INFO] Booting worker with pid: 1368078
[2022-10-18 17:50:38 +0700] [1368079] [INFO] Booting worker with pid: 1368079
[2022-10-18 17:50:38 +0700] [1368080] [INFO] Booting worker with pid: 1368080
[2022-10-18 17:50:38 +0700] [1368081] [INFO] Booting worker with pid: 1368081
[2022-10-18 17:50:42 +0700] [1368079] [INFO] Started server process [1368079]
[2022-10-18 17:50:42 +0700] [1368081] [INFO] Started server process [1368081]
[2022-10-18 17:50:42 +0700] [1368078] [INFO] Started server process [1368078]
[2022-10-18 17:50:42 +0700] [1368079] [INFO] Waiting for application startup.
[2022-10-18 17:50:42 +0700] [1368081] [INFO] Waiting for application startup.
[2022-10-18 17:50:42 +0700] [1368078] [INFO] Waiting for application startup.
[2022-10-18 17:50:42 +0700] [1368080] [INFO] Started server process [1368080]
[2022-10-18 17:50:42 +0700] [1368080] [INFO] Waiting for application startup.
[2022-10-18 17:50:42 +0700] [1368079] [INFO] Application startup complete.
[2022-10-18 17:50:42 +0700] [1368081] [INFO] Application startup complete.
[2022-10-18 17:50:42 +0700] [1368078] [INFO] Application startup complete.
[2022-10-18 17:50:42 +0700] [1368080] [INFO] Application startup complete.
[2022-10-18 18:22:01 +0700] [1369001] [INFO] Starting gunicorn 20.1.0
[2022-10-18 18:22:01 +0700] [1369001] [INFO] Listening at: http://10.242.184.93:8000 (1369001)
[2022-10-18 18:22:01 +0700] [1369001] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-10-18 18:22:01 +0700] [1369003] [INFO] Booting worker with pid: 1369003
[2022-10-18 18:22:01 +0700] [1369004] [INFO] Booting worker with pid: 1369004
[2022-10-18 18:22:01 +0700] [1369005] [INFO] Booting worker with pid: 1369005
[2022-10-18 18:22:01 +0700] [1369009] [INFO] Booting worker with pid: 1369009
[2022-10-18 18:22:03 +0700] [1369004] [INFO] Started server process [1369004]
[2022-10-18 18:22:03 +0700] [1369004] [INFO] Waiting for application startup.
[2022-10-18 18:22:03 +0700] [1369004] [INFO] Application startup complete.
[2022-10-18 18:22:03 +0700] [1369005] [INFO] Started server process [1369005]
[2022-10-18 18:22:03 +0700] [1369005] [INFO] Waiting for application startup.
[2022-10-18 18:22:03 +0700] [1369005] [INFO] Application startup complete.
[2022-10-18 18:22:03 +0700] [1369003] [INFO] Started server process [1369003]
[2022-10-18 18:22:03 +0700] [1369003] [INFO] Waiting for application startup.
[2022-10-18 18:22:03 +0700] [1369003] [INFO] Application startup complete.
[2022-10-18 18:22:03 +0700] [1369009] [INFO] Started server process [1369009]
[2022-10-18 18:22:03 +0700] [1369009] [INFO] Waiting for application startup.
[2022-10-18 18:22:03 +0700] [1369009] [INFO] Application startup complete.
[2022-10-18 18:24:19 +0700] [1369080] [INFO] Starting gunicorn 20.1.0
[2022-10-18 18:24:19 +0700] [1369080] [INFO] Listening at: http://10.242.184.93:443 (1369080)
[2022-10-18 18:24:19 +0700] [1369080] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-10-18 18:24:19 +0700] [1369082] [INFO] Booting worker with pid: 1369082
[2022-10-18 18:24:19 +0700] [1369083] [INFO] Booting worker with pid: 1369083
[2022-10-18 18:24:19 +0700] [1369087] [INFO] Booting worker with pid: 1369087
[2022-10-18 18:24:19 +0700] [1369091] [INFO] Booting worker with pid: 1369091
[2022-10-18 18:24:20 +0700] [1369082] [INFO] Started server process [1369082]
[2022-10-18 18:24:20 +0700] [1369082] [INFO] Waiting for application startup.
[2022-10-18 18:24:20 +0700] [1369082] [INFO] Application startup complete.
[2022-10-18 18:24:20 +0700] [1369083] [INFO] Started server process [1369083]
[2022-10-18 18:24:20 +0700] [1369083] [INFO] Waiting for application startup.
[2022-10-18 18:24:20 +0700] [1369083] [INFO] Application startup complete.
[2022-10-18 18:24:20 +0700] [1369091] [INFO] Started server process [1369091]
[2022-10-18 18:24:20 +0700] [1369091] [INFO] Waiting for application startup.
[2022-10-18 18:24:20 +0700] [1369091] [INFO] Application startup complete.
[2022-10-18 18:24:21 +0700] [1369087] [INFO] Started server process [1369087]
[2022-10-18 18:24:21 +0700] [1369087] [INFO] Waiting for application startup.
[2022-10-18 18:24:21 +0700] [1369087] [INFO] Application startup complete.
[2022-10-18 18:36:22 +0700] [1369594] [INFO] Starting gunicorn 20.1.0
[2022-10-18 18:36:22 +0700] [1369594] [INFO] Listening at: http://10.242.184.93:443 (1369594)
[2022-10-18 18:36:22 +0700] [1369594] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-10-18 18:36:22 +0700] [1369596] [INFO] Booting worker with pid: 1369596
[2022-10-18 18:36:22 +0700] [1369597] [INFO] Booting worker with pid: 1369597
[2022-10-18 18:36:23 +0700] [1369601] [INFO] Booting worker with pid: 1369601
[2022-10-18 18:36:23 +0700] [1369605] [INFO] Booting worker with pid: 1369605
[2022-10-18 18:36:24 +0700] [1369596] [INFO] Started server process [1369596]
[2022-10-18 18:36:24 +0700] [1369596] [INFO] Waiting for application startup.
[2022-10-18 18:36:24 +0700] [1369596] [INFO] Application startup complete.
[2022-10-18 18:36:24 +0700] [1369597] [INFO] Started server process [1369597]
[2022-10-18 18:36:24 +0700] [1369597] [INFO] Waiting for application startup.
[2022-10-18 18:36:24 +0700] [1369597] [INFO] Application startup complete.
[2022-10-18 18:36:24 +0700] [1369601] [INFO] Started server process [1369601]
[2022-10-18 18:36:24 +0700] [1369601] [INFO] Waiting for application startup.
[2022-10-18 18:36:24 +0700] [1369601] [INFO] Application startup complete.
[2022-10-18 18:36:24 +0700] [1369605] [INFO] Started server process [1369605]
[2022-10-18 18:36:24 +0700] [1369605] [INFO] Waiting for application startup.
[2022-10-18 18:36:24 +0700] [1369605] [INFO] Application startup complete.
[2022-11-07 16:04:39 +0700] [1369594] [INFO] Handling signal: term
[2022-11-07 16:04:39 +0700] [1369594] [WARNING] Worker with pid 1369605 was terminated due to signal 1
[2022-11-07 16:04:39 +0700] [1369594] [WARNING] Worker with pid 1369597 was terminated due to signal 1
[2022-11-07 16:04:39 +0700] [1369594] [WARNING] Worker with pid 1369601 was terminated due to signal 1
[2022-11-07 16:04:39 +0700] [1369594] [WARNING] Worker with pid 1369596 was terminated due to signal 1
[2022-11-07 16:04:39 +0700] [1369594] [INFO] Shutting down: Master
[2022-11-09 02:01:04 +0700] [2184] [INFO] Starting gunicorn 20.1.0
[2022-11-09 02:01:04 +0700] [2184] [INFO] Listening at: http://10.242.184.93:443 (2184)
[2022-11-09 02:01:04 +0700] [2184] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-09 02:01:04 +0700] [2186] [INFO] Booting worker with pid: 2186
[2022-11-09 02:01:04 +0700] [2187] [INFO] Booting worker with pid: 2187
[2022-11-09 02:01:04 +0700] [2188] [INFO] Booting worker with pid: 2188
[2022-11-09 02:01:04 +0700] [2189] [INFO] Booting worker with pid: 2189
[2022-11-09 02:01:08 +0700] [2187] [INFO] Started server process [2187]
[2022-11-09 02:01:08 +0700] [2188] [INFO] Started server process [2188]
[2022-11-09 02:01:08 +0700] [2186] [INFO] Started server process [2186]
[2022-11-09 02:01:08 +0700] [2187] [INFO] Waiting for application startup.
[2022-11-09 02:01:08 +0700] [2188] [INFO] Waiting for application startup.
[2022-11-09 02:01:08 +0700] [2189] [INFO] Started server process [2189]
[2022-11-09 02:01:08 +0700] [2186] [INFO] Waiting for application startup.
[2022-11-09 02:01:08 +0700] [2189] [INFO] Waiting for application startup.
[2022-11-09 02:01:08 +0700] [2187] [INFO] Application startup complete.
[2022-11-09 02:01:08 +0700] [2188] [INFO] Application startup complete.
[2022-11-09 02:01:08 +0700] [2186] [INFO] Application startup complete.
[2022-11-09 02:01:08 +0700] [2189] [INFO] Application startup complete.
[2022-11-09 02:06:58 +0700] [2401] [INFO] Starting gunicorn 20.1.0
[2022-11-09 02:06:58 +0700] [2401] [INFO] Listening at: http://10.242.184.93:443 (2401)
[2022-11-09 02:06:58 +0700] [2400] [INFO] Starting gunicorn 20.1.0
[2022-11-09 02:06:58 +0700] [2401] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-09 02:06:58 +0700] [2400] [ERROR] Connection in use: ('10.242.184.93', 443)
[2022-11-09 02:06:58 +0700] [2400] [ERROR] Retrying in 1 second.
[2022-11-09 02:06:58 +0700] [2404] [INFO] Booting worker with pid: 2404
[2022-11-09 02:06:58 +0700] [2405] [INFO] Booting worker with pid: 2405
[2022-11-09 02:06:58 +0700] [2406] [INFO] Booting worker with pid: 2406
[2022-11-09 02:06:58 +0700] [2407] [INFO] Booting worker with pid: 2407
[2022-11-09 02:06:59 +0700] [2400] [ERROR] Connection in use: ('10.242.184.93', 443)
[2022-11-09 02:06:59 +0700] [2400] [ERROR] Retrying in 1 second.
[2022-11-09 02:06:59 +0700] [2406] [INFO] Started server process [2406]
[2022-11-09 02:06:59 +0700] [2406] [INFO] Waiting for application startup.
[2022-11-09 02:06:59 +0700] [2406] [INFO] Application startup complete.
[2022-11-09 02:06:59 +0700] [2405] [INFO] Started server process [2405]
[2022-11-09 02:06:59 +0700] [2405] [INFO] Waiting for application startup.
[2022-11-09 02:06:59 +0700] [2405] [INFO] Application startup complete.
[2022-11-09 02:06:59 +0700] [2407] [INFO] Started server process [2407]
[2022-11-09 02:06:59 +0700] [2407] [INFO] Waiting for application startup.
[2022-11-09 02:06:59 +0700] [2407] [INFO] Application startup complete.
[2022-11-09 02:06:59 +0700] [2404] [INFO] Started server process [2404]
[2022-11-09 02:06:59 +0700] [2404] [INFO] Waiting for application startup.
[2022-11-09 02:06:59 +0700] [2404] [INFO] Application startup complete.
[2022-11-09 02:07:00 +0700] [2400] [ERROR] Connection in use: ('10.242.184.93', 443)
[2022-11-09 02:07:00 +0700] [2400] [ERROR] Retrying in 1 second.
[2022-11-09 02:07:01 +0700] [2400] [ERROR] Connection in use: ('10.242.184.93', 443)
[2022-11-09 02:07:01 +0700] [2400] [ERROR] Retrying in 1 second.
[2022-11-09 02:07:02 +0700] [2400] [ERROR] Connection in use: ('10.242.184.93', 443)
[2022-11-09 02:07:02 +0700] [2400] [ERROR] Retrying in 1 second.
[2022-11-09 02:07:03 +0700] [2400] [ERROR] Can't connect to ('10.242.184.93', 443)
 UPDATE  The latest version of `serve` is 14.1.0.
INFO: Accepting connections at http://localhost:80.
 UPDATE  The latest version of `serve` is 14.1.0.
INFO: Accepting connections at http://localhost:80.
[2022-11-09 02:21:20 +0700] [3041] [INFO] Starting gunicorn 20.1.0
[2022-11-09 02:21:20 +0700] [3041] [INFO] Listening at: http://10.242.184.93:443 (3041)
[2022-11-09 02:21:20 +0700] [3041] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-09 02:21:20 +0700] [3054] [INFO] Booting worker with pid: 3054
[2022-11-09 02:21:20 +0700] [3054] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '/home/pusintek/dupakq/main'
[2022-11-09 02:21:20 +0700] [3054] [INFO] Worker exiting (pid: 3054)
[2022-11-09 02:21:20 +0700] [3041] [INFO] Shutting down: Master
[2022-11-09 02:21:20 +0700] [3041] [INFO] Reason: Worker failed to boot.
[2022-11-09 02:23:11 +0700] [3117] [INFO] Starting gunicorn 20.1.0
[2022-11-09 02:23:11 +0700] [3117] [INFO] Listening at: http://10.242.184.93:443 (3117)
[2022-11-09 02:23:11 +0700] [3117] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-09 02:23:11 +0700] [3119] [INFO] Booting worker with pid: 3119
[2022-11-09 02:23:11 +0700] [3119] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '/home/pusintek/dupakq/main'
[2022-11-09 02:23:11 +0700] [3119] [INFO] Worker exiting (pid: 3119)
[2022-11-09 02:23:11 +0700] [3117] [INFO] Shutting down: Master
[2022-11-09 02:23:11 +0700] [3117] [INFO] Reason: Worker failed to boot.
 UPDATE  The latest version of `serve` is 14.1.0.
[2022-11-09 02:27:52 +0700] [3273] [INFO] Starting gunicorn 20.1.0
[2022-11-09 02:27:52 +0700] [3273] [INFO] Listening at: http://10.242.184.93:443 (3273)
[2022-11-09 02:27:52 +0700] [3273] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-09 02:27:52 +0700] [3286] [INFO] Booting worker with pid: 3286
INFO: Accepting connections at http://localhost:80.
[2022-11-09 02:27:52 +0700] [3287] [INFO] Booting worker with pid: 3287
[2022-11-09 02:27:52 +0700] [3288] [INFO] Booting worker with pid: 3288
[2022-11-09 02:27:52 +0700] [3292] [INFO] Booting worker with pid: 3292
[2022-11-09 02:27:54 +0700] [3287] [INFO] Started server process [3287]
[2022-11-09 02:27:54 +0700] [3287] [INFO] Waiting for application startup.
[2022-11-09 02:27:54 +0700] [3287] [INFO] Application startup complete.
[2022-11-09 02:27:54 +0700] [3288] [INFO] Started server process [3288]
[2022-11-09 02:27:54 +0700] [3288] [INFO] Waiting for application startup.
[2022-11-09 02:27:54 +0700] [3288] [INFO] Application startup complete.
[2022-11-09 02:27:54 +0700] [3286] [INFO] Started server process [3286]
[2022-11-09 02:27:54 +0700] [3286] [INFO] Waiting for application startup.
[2022-11-09 02:27:54 +0700] [3286] [INFO] Application startup complete.
[2022-11-09 02:27:54 +0700] [3292] [INFO] Started server process [3292]
[2022-11-09 02:27:54 +0700] [3292] [INFO] Waiting for application startup.
[2022-11-09 02:27:54 +0700] [3292] [INFO] Application startup complete.
[2022-11-09 02:32:32 +0700] [3474] [INFO] Starting gunicorn 20.1.0
[2022-11-09 02:32:32 +0700] [3474] [INFO] Listening at: http://10.242.184.93:443 (3474)
[2022-11-09 02:32:32 +0700] [3474] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-09 02:32:32 +0700] [3487] [INFO] Booting worker with pid: 3487
[2022-11-09 02:32:32 +0700] [3488] [INFO] Booting worker with pid: 3488
[2022-11-09 02:32:32 +0700] [3489] [INFO] Booting worker with pid: 3489
[2022-11-09 02:32:32 +0700] [3490] [INFO] Booting worker with pid: 3490
[2022-11-09 02:32:34 +0700] [3487] [INFO] Started server process [3487]
[2022-11-09 02:32:34 +0700] [3487] [INFO] Waiting for application startup.
[2022-11-09 02:32:34 +0700] [3487] [INFO] Application startup complete.
[2022-11-09 02:32:34 +0700] [3488] [INFO] Started server process [3488]
[2022-11-09 02:32:34 +0700] [3488] [INFO] Waiting for application startup.
[2022-11-09 02:32:34 +0700] [3488] [INFO] Application startup complete.
[2022-11-09 02:32:34 +0700] [3490] [INFO] Started server process [3490]
[2022-11-09 02:32:34 +0700] [3490] [INFO] Waiting for application startup.
[2022-11-09 02:32:34 +0700] [3490] [INFO] Application startup complete.
[2022-11-09 02:32:34 +0700] [3489] [INFO] Started server process [3489]
[2022-11-09 02:32:34 +0700] [3489] [INFO] Waiting for application startup.
[2022-11-09 02:32:34 +0700] [3489] [INFO] Application startup complete.
[2022-11-09 02:40:14 +0700] [3474] [INFO] Handling signal: term
[2022-11-09 02:40:14 +0700] [3474] [WARNING] Worker with pid 3487 was terminated due to signal 1
[2022-11-09 02:40:14 +0700] [3474] [WARNING] Worker with pid 3490 was terminated due to signal 1
[2022-11-09 02:40:14 +0700] [3474] [WARNING] Worker with pid 3488 was terminated due to signal 1
[2022-11-09 02:40:14 +0700] [3474] [WARNING] Worker with pid 3489 was terminated due to signal 1
[2022-11-09 02:40:14 +0700] [3474] [INFO] Shutting down: Master
[2022-11-09 02:43:11 +0700] [1831] [INFO] Starting gunicorn 20.1.0
[2022-11-09 02:43:11 +0700] [1831] [INFO] Listening at: http://10.242.184.93:443 (1831)
[2022-11-09 02:43:11 +0700] [1831] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-09 02:43:11 +0700] [1844] [INFO] Booting worker with pid: 1844
[2022-11-09 02:43:11 +0700] [1845] [INFO] Booting worker with pid: 1845
[2022-11-09 02:43:11 +0700] [1846] [INFO] Booting worker with pid: 1846
[2022-11-09 02:43:11 +0700] [1847] [INFO] Booting worker with pid: 1847
[2022-11-09 02:43:17 +0700] [1845] [INFO] Started server process [1845]
[2022-11-09 02:43:17 +0700] [1846] [INFO] Started server process [1846]
[2022-11-09 02:43:17 +0700] [1847] [INFO] Started server process [1847]
[2022-11-09 02:43:17 +0700] [1844] [INFO] Started server process [1844]
[2022-11-09 02:43:17 +0700] [1845] [INFO] Waiting for application startup.
[2022-11-09 02:43:17 +0700] [1846] [INFO] Waiting for application startup.
[2022-11-09 02:43:17 +0700] [1847] [INFO] Waiting for application startup.
[2022-11-09 02:43:17 +0700] [1844] [INFO] Waiting for application startup.
[2022-11-09 02:43:17 +0700] [1846] [INFO] Application startup complete.
[2022-11-09 02:43:17 +0700] [1845] [INFO] Application startup complete.
[2022-11-09 02:43:17 +0700] [1847] [INFO] Application startup complete.
[2022-11-09 02:43:17 +0700] [1844] [INFO] Application startup complete.
[2022-11-09 02:49:16 +0700] [1831] [INFO] Handling signal: term
[2022-11-09 02:49:16 +0700] [1831] [WARNING] Worker with pid 1845 was terminated due to signal 1
[2022-11-09 02:49:16 +0700] [1831] [WARNING] Worker with pid 1847 was terminated due to signal 1
[2022-11-09 02:49:16 +0700] [1831] [WARNING] Worker with pid 1846 was terminated due to signal 1
[2022-11-09 02:49:16 +0700] [1831] [WARNING] Worker with pid 1844 was terminated due to signal 1
[2022-11-09 02:49:16 +0700] [1831] [INFO] Shutting down: Master
[2022-11-09 02:51:18 +0700] [1816] [INFO] Starting gunicorn 20.1.0
[2022-11-09 02:51:18 +0700] [1816] [INFO] Listening at: http://10.242.184.93:443 (1816)
[2022-11-09 02:51:18 +0700] [1816] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-09 02:51:18 +0700] [1829] [INFO] Booting worker with pid: 1829
[2022-11-09 02:51:18 +0700] [1830] [INFO] Booting worker with pid: 1830
[2022-11-09 02:51:18 +0700] [1831] [INFO] Booting worker with pid: 1831
[2022-11-09 02:51:18 +0700] [1832] [INFO] Booting worker with pid: 1832
[2022-11-09 02:51:22 +0700] [1832] [INFO] Started server process [1832]
[2022-11-09 02:51:22 +0700] [1830] [INFO] Started server process [1830]
[2022-11-09 02:51:22 +0700] [1831] [INFO] Started server process [1831]
[2022-11-09 02:51:22 +0700] [1832] [INFO] Waiting for application startup.
[2022-11-09 02:51:22 +0700] [1830] [INFO] Waiting for application startup.
[2022-11-09 02:51:22 +0700] [1829] [INFO] Started server process [1829]
[2022-11-09 02:51:22 +0700] [1831] [INFO] Waiting for application startup.
[2022-11-09 02:51:22 +0700] [1829] [INFO] Waiting for application startup.
[2022-11-09 02:51:22 +0700] [1830] [INFO] Application startup complete.
[2022-11-09 02:51:22 +0700] [1832] [INFO] Application startup complete.
[2022-11-09 02:51:22 +0700] [1831] [INFO] Application startup complete.
[2022-11-09 02:51:22 +0700] [1829] [INFO] Application startup complete.
[2022-11-09 02:53:06 +0700] [1816] [INFO] Handling signal: term
[2022-11-09 02:53:06 +0700] [1816] [WARNING] Worker with pid 1830 was terminated due to signal 1
[2022-11-09 02:53:06 +0700] [1816] [WARNING] Worker with pid 1829 was terminated due to signal 1
[2022-11-09 02:53:06 +0700] [1816] [WARNING] Worker with pid 1832 was terminated due to signal 1
[2022-11-09 02:53:06 +0700] [1816] [WARNING] Worker with pid 1831 was terminated due to signal 1
[2022-11-09 02:53:06 +0700] [1816] [INFO] Shutting down: Master
[2022-11-09 02:55:12 +0700] [1820] [INFO] Starting gunicorn 20.1.0
[2022-11-09 02:55:12 +0700] [1820] [INFO] Listening at: http://10.242.184.93:443 (1820)
[2022-11-09 02:55:12 +0700] [1820] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-09 02:55:12 +0700] [1833] [INFO] Booting worker with pid: 1833
[2022-11-09 02:55:12 +0700] [1834] [INFO] Booting worker with pid: 1834
[2022-11-09 02:55:12 +0700] [1835] [INFO] Booting worker with pid: 1835
[2022-11-09 02:55:12 +0700] [1836] [INFO] Booting worker with pid: 1836
[2022-11-09 02:55:16 +0700] [1833] [INFO] Started server process [1833]
[2022-11-09 02:55:16 +0700] [1836] [INFO] Started server process [1836]
[2022-11-09 02:55:16 +0700] [1835] [INFO] Started server process [1835]
[2022-11-09 02:55:16 +0700] [1833] [INFO] Waiting for application startup.
[2022-11-09 02:55:16 +0700] [1836] [INFO] Waiting for application startup.
[2022-11-09 02:55:16 +0700] [1835] [INFO] Waiting for application startup.
[2022-11-09 02:55:16 +0700] [1834] [INFO] Started server process [1834]
[2022-11-09 02:55:16 +0700] [1834] [INFO] Waiting for application startup.
[2022-11-09 02:55:16 +0700] [1833] [INFO] Application startup complete.
[2022-11-09 02:55:16 +0700] [1836] [INFO] Application startup complete.
[2022-11-09 02:55:16 +0700] [1835] [INFO] Application startup complete.
[2022-11-09 02:55:16 +0700] [1834] [INFO] Application startup complete.
[2022-11-09 03:02:08 +0700] [2094] [INFO] Starting gunicorn 20.1.0
[2022-11-09 03:02:08 +0700] [2094] [INFO] Listening at: http://10.242.184.93:443 (2094)
[2022-11-09 03:02:08 +0700] [2094] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-09 03:02:08 +0700] [2107] [INFO] Booting worker with pid: 2107
[2022-11-09 03:02:08 +0700] [2108] [INFO] Booting worker with pid: 2108
[2022-11-09 03:02:08 +0700] [2109] [INFO] Booting worker with pid: 2109
[2022-11-09 03:02:08 +0700] [2113] [INFO] Booting worker with pid: 2113
[2022-11-09 03:02:09 +0700] [2107] [INFO] Started server process [2107]
[2022-11-09 03:02:09 +0700] [2107] [INFO] Waiting for application startup.
[2022-11-09 03:02:09 +0700] [2107] [INFO] Application startup complete.
[2022-11-09 03:02:09 +0700] [2108] [INFO] Started server process [2108]
[2022-11-09 03:02:09 +0700] [2108] [INFO] Waiting for application startup.
[2022-11-09 03:02:09 +0700] [2108] [INFO] Application startup complete.
[2022-11-09 03:02:09 +0700] [2113] [INFO] Started server process [2113]
[2022-11-09 03:02:09 +0700] [2113] [INFO] Waiting for application startup.
[2022-11-09 03:02:09 +0700] [2113] [INFO] Application startup complete.
[2022-11-09 03:02:09 +0700] [2109] [INFO] Started server process [2109]
[2022-11-09 03:02:09 +0700] [2109] [INFO] Waiting for application startup.
[2022-11-09 03:02:09 +0700] [2109] [INFO] Application startup complete.
[2022-11-09 03:02:39 +0700] [2094] [INFO] Handling signal: term
[2022-11-09 03:02:39 +0700] [2094] [WARNING] Worker with pid 2113 was terminated due to signal 1
[2022-11-09 03:02:39 +0700] [2094] [WARNING] Worker with pid 2108 was terminated due to signal 1
[2022-11-09 03:02:39 +0700] [2094] [WARNING] Worker with pid 2109 was terminated due to signal 1
[2022-11-09 03:02:39 +0700] [2094] [WARNING] Worker with pid 2107 was terminated due to signal 1
[2022-11-09 03:02:39 +0700] [2094] [INFO] Shutting down: Master
[2022-11-09 03:05:18 +0700] [1844] [INFO] Starting gunicorn 20.1.0
[2022-11-09 03:05:18 +0700] [1844] [INFO] Listening at: http://10.242.184.93:443 (1844)
[2022-11-09 03:05:18 +0700] [1844] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-09 03:05:18 +0700] [1857] [INFO] Booting worker with pid: 1857
[2022-11-09 03:05:18 +0700] [1858] [INFO] Booting worker with pid: 1858
[2022-11-09 03:05:18 +0700] [1859] [INFO] Booting worker with pid: 1859
[2022-11-09 03:05:18 +0700] [1860] [INFO] Booting worker with pid: 1860
[2022-11-09 03:05:22 +0700] [1859] [INFO] Started server process [1859]
[2022-11-09 03:05:22 +0700] [1859] [INFO] Waiting for application startup.
[2022-11-09 03:05:22 +0700] [1860] [INFO] Started server process [1860]
[2022-11-09 03:05:22 +0700] [1860] [INFO] Waiting for application startup.
[2022-11-09 03:05:22 +0700] [1859] [INFO] Application startup complete.
[2022-11-09 03:05:22 +0700] [1858] [INFO] Started server process [1858]
[2022-11-09 03:05:22 +0700] [1858] [INFO] Waiting for application startup.
[2022-11-09 03:05:22 +0700] [1860] [INFO] Application startup complete.
[2022-11-09 03:05:22 +0700] [1858] [INFO] Application startup complete.
[2022-11-09 03:05:22 +0700] [1857] [INFO] Started server process [1857]
[2022-11-09 03:05:22 +0700] [1857] [INFO] Waiting for application startup.
[2022-11-09 03:05:22 +0700] [1857] [INFO] Application startup complete.
[2022-11-09 03:06:08 +0700] [1925] [INFO] Starting gunicorn 20.1.0
[2022-11-09 03:06:08 +0700] [1925] [INFO] Listening at: http://10.242.184.93:443 (1925)
[2022-11-09 03:06:08 +0700] [1925] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-09 03:06:08 +0700] [1938] [INFO] Booting worker with pid: 1938
[2022-11-09 03:06:08 +0700] [1939] [INFO] Booting worker with pid: 1939
[2022-11-09 03:06:08 +0700] [1940] [INFO] Booting worker with pid: 1940
[2022-11-09 03:06:08 +0700] [1941] [INFO] Booting worker with pid: 1941
[2022-11-09 03:06:10 +0700] [1938] [INFO] Started server process [1938]
[2022-11-09 03:06:10 +0700] [1938] [INFO] Waiting for application startup.
[2022-11-09 03:06:10 +0700] [1938] [INFO] Application startup complete.
[2022-11-09 03:06:10 +0700] [1939] [INFO] Started server process [1939]
[2022-11-09 03:06:10 +0700] [1939] [INFO] Waiting for application startup.
[2022-11-09 03:06:10 +0700] [1939] [INFO] Application startup complete.
[2022-11-09 03:06:10 +0700] [1940] [INFO] Started server process [1940]
[2022-11-09 03:06:10 +0700] [1940] [INFO] Waiting for application startup.
[2022-11-09 03:06:10 +0700] [1940] [INFO] Application startup complete.
[2022-11-09 03:06:10 +0700] [1941] [INFO] Started server process [1941]
[2022-11-09 03:06:10 +0700] [1941] [INFO] Waiting for application startup.
[2022-11-09 03:06:10 +0700] [1941] [INFO] Application startup complete.
/home/pusintek/miniconda3/bin/python: No module named gunicorn
[2022-11-09 03:21:54 +0700] [2442] [INFO] Starting gunicorn 20.1.0
[2022-11-09 03:21:54 +0700] [2442] [INFO] Listening at: http://10.242.184.93:443 (2442)
[2022-11-09 03:21:54 +0700] [2442] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-09 03:21:54 +0700] [2457] [INFO] Booting worker with pid: 2457
[2022-11-09 03:21:54 +0700] [2458] [INFO] Booting worker with pid: 2458
[2022-11-09 03:21:54 +0700] [2462] [INFO] Booting worker with pid: 2462
[2022-11-09 03:21:54 +0700] [2466] [INFO] Booting worker with pid: 2466
[2022-11-09 03:21:56 +0700] [2458] [INFO] Started server process [2458]
[2022-11-09 03:21:56 +0700] [2458] [INFO] Waiting for application startup.
[2022-11-09 03:21:56 +0700] [2458] [INFO] Application startup complete.
[2022-11-09 03:21:56 +0700] [2457] [INFO] Started server process [2457]
[2022-11-09 03:21:56 +0700] [2457] [INFO] Waiting for application startup.
[2022-11-09 03:21:56 +0700] [2457] [INFO] Application startup complete.
[2022-11-09 03:21:56 +0700] [2462] [INFO] Started server process [2462]
[2022-11-09 03:21:56 +0700] [2462] [INFO] Waiting for application startup.
[2022-11-09 03:21:56 +0700] [2462] [INFO] Application startup complete.
[2022-11-09 03:21:56 +0700] [2466] [INFO] Started server process [2466]
[2022-11-09 03:21:56 +0700] [2466] [INFO] Waiting for application startup.
[2022-11-09 03:21:56 +0700] [2466] [INFO] Application startup complete.
[2022-11-09 04:50:21 +0700] [5071] [INFO] Starting gunicorn 20.1.0
[2022-11-09 04:50:21 +0700] [5071] [INFO] Listening at: http://10.242.184.93:443 (5071)
[2022-11-09 04:50:21 +0700] [5071] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-09 04:50:21 +0700] [5086] [INFO] Booting worker with pid: 5086
[2022-11-09 04:50:21 +0700] [5087] [INFO] Booting worker with pid: 5087
[2022-11-09 04:50:21 +0700] [5088] [INFO] Booting worker with pid: 5088
[2022-11-09 04:50:21 +0700] [5095] [INFO] Booting worker with pid: 5095
[2022-11-09 04:50:23 +0700] [5087] [INFO] Started server process [5087]
[2022-11-09 04:50:23 +0700] [5087] [INFO] Waiting for application startup.
[2022-11-09 04:50:23 +0700] [5087] [INFO] Application startup complete.
[2022-11-09 04:50:23 +0700] [5086] [INFO] Started server process [5086]
[2022-11-09 04:50:23 +0700] [5086] [INFO] Waiting for application startup.
[2022-11-09 04:50:23 +0700] [5086] [INFO] Application startup complete.
[2022-11-09 04:50:23 +0700] [5088] [INFO] Started server process [5088]
[2022-11-09 04:50:23 +0700] [5088] [INFO] Waiting for application startup.
[2022-11-09 04:50:23 +0700] [5088] [INFO] Application startup complete.
[2022-11-09 04:50:23 +0700] [5095] [INFO] Started server process [5095]
[2022-11-09 04:50:23 +0700] [5095] [INFO] Waiting for application startup.
[2022-11-09 04:50:23 +0700] [5095] [INFO] Application startup complete.
[2022-12-19 09:46:00 +0700] [25875] [INFO] Starting gunicorn 20.1.0
[2022-12-19 09:46:00 +0700] [25875] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:46:00 +0700] [25875] [ERROR] Retrying in 1 second.
[2022-12-19 09:46:01 +0700] [25875] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:46:01 +0700] [25875] [ERROR] Retrying in 1 second.
[2022-12-19 09:46:02 +0700] [25875] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:46:02 +0700] [25875] [ERROR] Retrying in 1 second.
[2022-12-19 09:46:03 +0700] [25875] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:46:03 +0700] [25875] [ERROR] Retrying in 1 second.
[2022-12-19 09:46:04 +0700] [25875] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:46:04 +0700] [25875] [ERROR] Retrying in 1 second.
[2022-12-19 09:46:05 +0700] [25875] [ERROR] Can't connect to ('10.242.184.93', 8000)
[2022-12-19 09:46:49 +0700] [25903] [INFO] Starting gunicorn 20.1.0
[2022-12-19 09:46:49 +0700] [25903] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:46:49 +0700] [25903] [ERROR] Retrying in 1 second.
[2022-12-19 09:46:50 +0700] [25903] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:46:50 +0700] [25903] [ERROR] Retrying in 1 second.
[2022-12-19 09:46:51 +0700] [25903] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:46:51 +0700] [25903] [ERROR] Retrying in 1 second.
[2022-12-19 09:46:52 +0700] [25903] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:46:52 +0700] [25903] [ERROR] Retrying in 1 second.
[2022-12-19 09:46:53 +0700] [25903] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:46:53 +0700] [25903] [ERROR] Retrying in 1 second.
[2022-12-19 09:46:54 +0700] [25903] [ERROR] Can't connect to ('10.242.184.93', 8000)
[2022-12-19 09:49:29 +0700] [25983] [INFO] Starting gunicorn 20.1.0
[2022-12-19 09:49:29 +0700] [25983] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:49:29 +0700] [25983] [ERROR] Retrying in 1 second.
[2022-12-19 09:49:30 +0700] [25983] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:49:30 +0700] [25983] [ERROR] Retrying in 1 second.
[2022-12-19 09:49:31 +0700] [25983] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:49:31 +0700] [25983] [ERROR] Retrying in 1 second.
[2022-12-19 09:49:32 +0700] [25983] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:49:32 +0700] [25983] [ERROR] Retrying in 1 second.
[2022-12-19 09:49:33 +0700] [25983] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:49:33 +0700] [25983] [ERROR] Retrying in 1 second.
[2022-12-19 09:49:34 +0700] [25983] [ERROR] Can't connect to ('10.242.184.93', 8000)
[2022-12-19 09:51:13 +0700] [26036] [INFO] Starting gunicorn 20.1.0
[2022-12-19 09:51:13 +0700] [26036] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:51:13 +0700] [26036] [ERROR] Retrying in 1 second.
[2022-12-19 09:51:14 +0700] [26036] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:51:14 +0700] [26036] [ERROR] Retrying in 1 second.
[2022-12-19 09:51:15 +0700] [26036] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:51:15 +0700] [26036] [ERROR] Retrying in 1 second.
[2022-12-19 09:51:16 +0700] [26036] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:51:16 +0700] [26036] [ERROR] Retrying in 1 second.
[2022-12-19 09:51:17 +0700] [26036] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:51:17 +0700] [26036] [ERROR] Retrying in 1 second.
[2022-12-19 09:51:18 +0700] [26036] [ERROR] Can't connect to ('10.242.184.93', 8000)
/Users/anandri/miniconda3/bin/python: No module named gunicorn
[2022-12-19 09:58:33 +0700] [26956] [INFO] Starting gunicorn 20.1.0
[2022-12-19 09:58:33 +0700] [26956] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:58:33 +0700] [26956] [ERROR] Retrying in 1 second.
[2022-12-19 09:58:34 +0700] [26956] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:58:34 +0700] [26956] [ERROR] Retrying in 1 second.
[2022-12-19 09:58:35 +0700] [26956] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:58:35 +0700] [26956] [ERROR] Retrying in 1 second.
[2022-12-19 09:58:36 +0700] [26956] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:58:36 +0700] [26956] [ERROR] Retrying in 1 second.
[2022-12-19 09:58:37 +0700] [26956] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 09:58:37 +0700] [26956] [ERROR] Retrying in 1 second.
[2022-12-19 09:58:38 +0700] [26956] [ERROR] Can't connect to ('10.242.184.93', 8000)
[2022-12-19 10:05:29 +0700] [27840] [INFO] Starting gunicorn 20.1.0
[2022-12-19 10:05:29 +0700] [27840] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:05:29 +0700] [27840] [ERROR] Retrying in 1 second.
[2022-12-19 10:05:30 +0700] [27840] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:05:30 +0700] [27840] [ERROR] Retrying in 1 second.
[2022-12-19 10:05:31 +0700] [27840] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:05:31 +0700] [27840] [ERROR] Retrying in 1 second.
[2022-12-19 10:05:32 +0700] [27840] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:05:32 +0700] [27840] [ERROR] Retrying in 1 second.
[2022-12-19 10:05:33 +0700] [27840] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:05:33 +0700] [27840] [ERROR] Retrying in 1 second.
[2022-12-19 10:05:34 +0700] [27840] [ERROR] Can't connect to ('10.242.184.93', 8000)
[2022-12-19 10:06:37 +0700] [28261] [INFO] Starting gunicorn 20.1.0
[2022-12-19 10:06:37 +0700] [28261] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:06:37 +0700] [28261] [ERROR] Retrying in 1 second.
[2022-12-19 10:06:38 +0700] [28261] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:06:38 +0700] [28261] [ERROR] Retrying in 1 second.
[2022-12-19 10:06:39 +0700] [28261] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:06:39 +0700] [28261] [ERROR] Retrying in 1 second.
[2022-12-19 10:06:40 +0700] [28261] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:06:40 +0700] [28261] [ERROR] Retrying in 1 second.
[2022-12-19 10:06:41 +0700] [28261] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:06:41 +0700] [28261] [ERROR] Retrying in 1 second.
[2022-12-19 10:06:42 +0700] [28261] [ERROR] Can't connect to ('10.242.184.93', 8000)
[2022-12-19 10:08:46 +0700] [29048] [INFO] Starting gunicorn 20.1.0
[2022-12-19 10:08:46 +0700] [29048] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:08:46 +0700] [29048] [ERROR] Retrying in 1 second.
[2022-12-19 10:08:47 +0700] [29048] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:08:47 +0700] [29048] [ERROR] Retrying in 1 second.
[2022-12-19 10:08:48 +0700] [29048] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:08:48 +0700] [29048] [ERROR] Retrying in 1 second.
[2022-12-19 10:08:49 +0700] [29048] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:08:49 +0700] [29048] [ERROR] Retrying in 1 second.
[2022-12-19 10:08:50 +0700] [29048] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:08:50 +0700] [29048] [ERROR] Retrying in 1 second.
[2022-12-19 10:08:51 +0700] [29048] [ERROR] Can't connect to ('10.242.184.93', 8000)
[2022-12-19 10:10:51 +0700] [29829] [INFO] Starting gunicorn 20.1.0
[2022-12-19 10:10:51 +0700] [29829] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:10:51 +0700] [29829] [ERROR] Retrying in 1 second.
[2022-12-19 10:10:52 +0700] [29829] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:10:52 +0700] [29829] [ERROR] Retrying in 1 second.
[2022-12-19 10:10:53 +0700] [29829] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:10:53 +0700] [29829] [ERROR] Retrying in 1 second.
[2022-12-19 10:10:54 +0700] [29829] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:10:54 +0700] [29829] [ERROR] Retrying in 1 second.
[2022-12-19 10:10:55 +0700] [29829] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:10:55 +0700] [29829] [ERROR] Retrying in 1 second.
[2022-12-19 10:10:56 +0700] [29829] [ERROR] Can't connect to ('10.242.184.93', 8000)
[2022-12-19 10:11:13 +0700] [30233] [INFO] Starting gunicorn 20.1.0
[2022-12-19 10:11:13 +0700] [30233] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:11:13 +0700] [30233] [ERROR] Retrying in 1 second.
[2022-12-19 10:11:14 +0700] [30233] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:11:14 +0700] [30233] [ERROR] Retrying in 1 second.
[2022-12-19 10:11:15 +0700] [30233] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:11:15 +0700] [30233] [ERROR] Retrying in 1 second.
[2022-12-19 10:11:16 +0700] [30233] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:11:16 +0700] [30233] [ERROR] Retrying in 1 second.
[2022-12-19 10:11:17 +0700] [30233] [ERROR] Invalid address: ('10.242.184.93', 8000)
[2022-12-19 10:11:17 +0700] [30233] [ERROR] Retrying in 1 second.
[2022-12-19 10:11:18 +0700] [30233] [ERROR] Can't connect to ('10.242.184.93', 8000)
[2023-03-07 09:24:50 +0700] [58933] [INFO] Starting gunicorn 20.1.0
[2023-03-07 09:24:50 +0700] [58933] [INFO] Listening at: http://0.0.0.0:443 (58933)
[2023-03-07 09:24:50 +0700] [58933] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-03-07 09:24:50 +0700] [58962] [INFO] Booting worker with pid: 58962
[2023-03-07 09:24:50 +0700] [58963] [INFO] Booting worker with pid: 58963
[2023-03-07 09:24:50 +0700] [58964] [INFO] Booting worker with pid: 58964
[2023-03-07 09:24:50 +0700] [58965] [INFO] Booting worker with pid: 58965
[2023-03-07 09:25:05 +0700] [58964] [INFO] Started server process [58964]
[2023-03-07 09:25:05 +0700] [58964] [INFO] Waiting for application startup.
[2023-03-07 09:25:05 +0700] [58964] [INFO] Application startup complete.
[2023-03-07 09:25:05 +0700] [58965] [INFO] Started server process [58965]
[2023-03-07 09:25:05 +0700] [58965] [INFO] Waiting for application startup.
[2023-03-07 09:25:05 +0700] [58965] [INFO] Application startup complete.
[2023-03-07 09:25:05 +0700] [58963] [INFO] Started server process [58963]
[2023-03-07 09:25:05 +0700] [58963] [INFO] Waiting for application startup.
[2023-03-07 09:25:05 +0700] [58963] [INFO] Application startup complete.
[2023-03-07 09:25:05 +0700] [58962] [INFO] Started server process [58962]
[2023-03-07 09:25:05 +0700] [58962] [INFO] Waiting for application startup.
[2023-03-07 09:25:05 +0700] [58962] [INFO] Application startup complete.
[2023-03-07 09:34:31 +0700] [71467] [INFO] Starting gunicorn 20.1.0
[2023-03-07 09:34:31 +0700] [71467] [INFO] Listening at: http://0.0.0.0:443 (71467)
[2023-03-07 09:34:31 +0700] [71467] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-03-07 09:34:31 +0700] [71481] [INFO] Booting worker with pid: 71481
[2023-03-07 09:34:31 +0700] [71482] [INFO] Booting worker with pid: 71482
[2023-03-07 09:34:31 +0700] [71484] [INFO] Booting worker with pid: 71484
[2023-03-07 09:34:31 +0700] [71485] [INFO] Booting worker with pid: 71485
[2023-03-07 09:34:37 +0700] [71481] [INFO] Started server process [71481]
[2023-03-07 09:34:37 +0700] [71481] [INFO] Waiting for application startup.
[2023-03-07 09:34:37 +0700] [71481] [INFO] Application startup complete.
[2023-03-07 09:34:37 +0700] [71482] [INFO] Started server process [71482]
[2023-03-07 09:34:37 +0700] [71482] [INFO] Waiting for application startup.
[2023-03-07 09:34:37 +0700] [71482] [INFO] Application startup complete.
[2023-03-07 09:34:37 +0700] [71485] [INFO] Started server process [71485]
[2023-03-07 09:34:37 +0700] [71485] [INFO] Waiting for application startup.
[2023-03-07 09:34:37 +0700] [71485] [INFO] Application startup complete.
[2023-03-07 09:34:37 +0700] [71484] [INFO] Started server process [71484]
[2023-03-07 09:34:37 +0700] [71484] [INFO] Waiting for application startup.
[2023-03-07 09:34:37 +0700] [71484] [INFO] Application startup complete.
[2023-03-07 09:54:58 +0700] [96160] [INFO] Starting gunicorn 20.1.0
[2023-03-07 09:54:58 +0700] [96160] [INFO] Listening at: http://10.242.77.105:443 (96160)
[2023-03-07 09:54:58 +0700] [96160] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-03-07 09:54:58 +0700] [96177] [INFO] Booting worker with pid: 96177
[2023-03-07 09:54:58 +0700] [96181] [INFO] Booting worker with pid: 96181
[2023-03-07 09:54:58 +0700] [96193] [INFO] Booting worker with pid: 96193
[2023-03-07 09:54:58 +0700] [96197] [INFO] Booting worker with pid: 96197
[2023-03-07 09:55:03 +0700] [96181] [INFO] Started server process [96181]
[2023-03-07 09:55:03 +0700] [96181] [INFO] Waiting for application startup.
[2023-03-07 09:55:03 +0700] [96181] [INFO] Application startup complete.
[2023-03-07 09:55:03 +0700] [96177] [INFO] Started server process [96177]
[2023-03-07 09:55:03 +0700] [96177] [INFO] Waiting for application startup.
[2023-03-07 09:55:03 +0700] [96177] [INFO] Application startup complete.
[2023-03-07 09:55:03 +0700] [96197] [INFO] Started server process [96197]
[2023-03-07 09:55:03 +0700] [96197] [INFO] Waiting for application startup.
[2023-03-07 09:55:03 +0700] [96197] [INFO] Application startup complete.
[2023-03-07 09:55:04 +0700] [96193] [INFO] Started server process [96193]
[2023-03-07 09:55:04 +0700] [96193] [INFO] Waiting for application startup.
[2023-03-07 09:55:04 +0700] [96193] [INFO] Application startup complete.
[2023-03-07 09:55:13 +0700] [96181] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 147, in _connect
    s.connect(resolved_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 284, in connect
    s = BoltSocket._connect(resolved_address, timeout, keep_alive)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 164, in _connect
    raise ServiceUnavailable(
neo4j.exceptions.ServiceUnavailable: Failed to establish connection to ResolvedIPv4Address(('10.242.77.105', 7687)) (reason [Errno 111] Connection refused)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/pusintek/project/dupakq/main.py", line 769, in query_graph2
    result = session.run("match p=(m)-[r]-(n) where toLower(m.label) contains '"+str(x[0]).lower()+"' \
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/work/simple.py", line 204, in run
    self._connect(self._config.default_access_mode)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/work/simple.py", line 108, in _connect
    super()._connect(access_mode)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/work/__init__.py", line 82, in _connect
    self._connection = self._pool.acquire(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 926, in acquire
    return self._acquire(self.address, deadline)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 801, in _acquire
    return connection_creator()
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 729, in connection_creator
    connection = self.opener(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 907, in opener
    return Bolt.open(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 327, in open
    s, pool_config.protocol_version, handshake, data = BoltSocket.connect(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 311, in connect
    raise ServiceUnavailable(
neo4j.exceptions.ServiceUnavailable: Couldn't connect to 10.242.77.105:7687 (resolved to ('10.242.77.105:7687',)):
Failed to establish connection to ResolvedIPv4Address(('10.242.77.105', 7687)) (reason [Errno 111] Connection refused)
[2023-03-07 09:55:16 +0700] [96193] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 147, in _connect
    s.connect(resolved_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 284, in connect
    s = BoltSocket._connect(resolved_address, timeout, keep_alive)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 164, in _connect
    raise ServiceUnavailable(
neo4j.exceptions.ServiceUnavailable: Failed to establish connection to ResolvedIPv4Address(('10.242.77.105', 7687)) (reason [Errno 111] Connection refused)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/pusintek/project/dupakq/main.py", line 769, in query_graph2
    result = session.run("match p=(m)-[r]-(n) where toLower(m.label) contains '"+str(x[0]).lower()+"' \
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/work/simple.py", line 204, in run
    self._connect(self._config.default_access_mode)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/work/simple.py", line 108, in _connect
    super()._connect(access_mode)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/work/__init__.py", line 82, in _connect
    self._connection = self._pool.acquire(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 926, in acquire
    return self._acquire(self.address, deadline)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 801, in _acquire
    return connection_creator()
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 729, in connection_creator
    connection = self.opener(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 907, in opener
    return Bolt.open(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 327, in open
    s, pool_config.protocol_version, handshake, data = BoltSocket.connect(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 311, in connect
    raise ServiceUnavailable(
neo4j.exceptions.ServiceUnavailable: Couldn't connect to 10.242.77.105:7687 (resolved to ('10.242.77.105:7687',)):
Failed to establish connection to ResolvedIPv4Address(('10.242.77.105', 7687)) (reason [Errno 111] Connection refused)
[2023-03-07 09:56:53 +0700] [100640] [INFO] Starting gunicorn 20.1.0
[2023-03-07 09:56:53 +0700] [100640] [INFO] Listening at: http://10.242.77.105:443 (100640)
[2023-03-07 09:56:53 +0700] [100640] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-03-07 09:56:53 +0700] [100660] [INFO] Booting worker with pid: 100660
[2023-03-07 09:56:53 +0700] [100661] [INFO] Booting worker with pid: 100661
[2023-03-07 09:56:53 +0700] [100662] [INFO] Booting worker with pid: 100662
[2023-03-07 09:56:53 +0700] [100663] [INFO] Booting worker with pid: 100663
[2023-03-07 09:56:57 +0700] [100660] [INFO] Started server process [100660]
[2023-03-07 09:56:57 +0700] [100660] [INFO] Waiting for application startup.
[2023-03-07 09:56:57 +0700] [100660] [INFO] Application startup complete.
[2023-03-07 09:56:58 +0700] [100661] [INFO] Started server process [100661]
[2023-03-07 09:56:58 +0700] [100661] [INFO] Waiting for application startup.
[2023-03-07 09:56:58 +0700] [100661] [INFO] Application startup complete.
[2023-03-07 09:56:58 +0700] [100663] [INFO] Started server process [100663]
[2023-03-07 09:56:58 +0700] [100663] [INFO] Waiting for application startup.
[2023-03-07 09:56:58 +0700] [100663] [INFO] Application startup complete.
[2023-03-07 09:56:58 +0700] [100662] [INFO] Started server process [100662]
[2023-03-07 09:56:58 +0700] [100662] [INFO] Waiting for application startup.
[2023-03-07 09:56:58 +0700] [100662] [INFO] Application startup complete.
[2023-03-07 10:54:14 +0700] [32891] [INFO] Starting gunicorn 20.1.0
[2023-03-07 10:54:14 +0700] [32891] [INFO] Listening at: http://10.242.77.105:443 (32891)
[2023-03-07 10:54:14 +0700] [32891] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-03-07 10:54:14 +0700] [32907] [INFO] Booting worker with pid: 32907
[2023-03-07 10:54:14 +0700] [32908] [INFO] Booting worker with pid: 32908
[2023-03-07 10:54:14 +0700] [32909] [INFO] Booting worker with pid: 32909
[2023-03-07 10:54:15 +0700] [32911] [INFO] Booting worker with pid: 32911
[2023-03-07 10:54:20 +0700] [32909] [INFO] Started server process [32909]
[2023-03-07 10:54:20 +0700] [32909] [INFO] Waiting for application startup.
[2023-03-07 10:54:20 +0700] [32909] [INFO] Application startup complete.
[2023-03-07 10:54:20 +0700] [32907] [INFO] Started server process [32907]
[2023-03-07 10:54:20 +0700] [32907] [INFO] Waiting for application startup.
[2023-03-07 10:54:20 +0700] [32907] [INFO] Application startup complete.
[2023-03-07 10:54:20 +0700] [32911] [INFO] Started server process [32911]
[2023-03-07 10:54:20 +0700] [32911] [INFO] Waiting for application startup.
[2023-03-07 10:54:20 +0700] [32911] [INFO] Application startup complete.
[2023-03-07 10:54:20 +0700] [32908] [INFO] Started server process [32908]
[2023-03-07 10:54:20 +0700] [32908] [INFO] Waiting for application startup.
[2023-03-07 10:54:20 +0700] [32908] [INFO] Application startup complete.
[2023-03-07 10:55:03 +0700] [32908] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 147, in _connect
    s.connect(resolved_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 284, in connect
    s = BoltSocket._connect(resolved_address, timeout, keep_alive)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 164, in _connect
    raise ServiceUnavailable(
neo4j.exceptions.ServiceUnavailable: Failed to establish connection to ResolvedIPv4Address(('10.242.77.105', 7687)) (reason [Errno 111] Connection refused)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/pusintek/project/dupakq/main.py", line 762, in query_graph2
    result = session.run("match p=(m)-[r]-(n) where toLower(m.label) contains '"+str(x[0]).lower()+"' \
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/work/simple.py", line 204, in run
    self._connect(self._config.default_access_mode)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/work/simple.py", line 108, in _connect
    super()._connect(access_mode)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/work/__init__.py", line 82, in _connect
    self._connection = self._pool.acquire(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 926, in acquire
    return self._acquire(self.address, deadline)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 801, in _acquire
    return connection_creator()
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 729, in connection_creator
    connection = self.opener(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 907, in opener
    return Bolt.open(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 327, in open
    s, pool_config.protocol_version, handshake, data = BoltSocket.connect(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 311, in connect
    raise ServiceUnavailable(
neo4j.exceptions.ServiceUnavailable: Couldn't connect to 10.242.77.105:7687 (resolved to ('10.242.77.105:7687',)):
Failed to establish connection to ResolvedIPv4Address(('10.242.77.105', 7687)) (reason [Errno 111] Connection refused)
[2023-03-07 11:11:56 +0700] [54020] [INFO] Starting gunicorn 20.1.0
[2023-03-07 11:11:56 +0700] [54020] [INFO] Listening at: http://10.242.77.105:443 (54020)
[2023-03-07 11:11:56 +0700] [54020] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-03-07 11:11:56 +0700] [54046] [INFO] Booting worker with pid: 54046
[2023-03-07 11:11:56 +0700] [54047] [INFO] Booting worker with pid: 54047
[2023-03-07 11:11:57 +0700] [54048] [INFO] Booting worker with pid: 54048
[2023-03-07 11:11:57 +0700] [54050] [INFO] Booting worker with pid: 54050
[2023-03-07 11:12:01 +0700] [54046] [INFO] Started server process [54046]
[2023-03-07 11:12:01 +0700] [54046] [INFO] Waiting for application startup.
[2023-03-07 11:12:01 +0700] [54046] [INFO] Application startup complete.
[2023-03-07 11:12:01 +0700] [54047] [INFO] Started server process [54047]
[2023-03-07 11:12:01 +0700] [54047] [INFO] Waiting for application startup.
[2023-03-07 11:12:01 +0700] [54047] [INFO] Application startup complete.
[2023-03-07 11:12:02 +0700] [54050] [INFO] Started server process [54050]
[2023-03-07 11:12:02 +0700] [54050] [INFO] Waiting for application startup.
[2023-03-07 11:12:02 +0700] [54050] [INFO] Application startup complete.
[2023-03-07 11:12:02 +0700] [54048] [INFO] Started server process [54048]
[2023-03-07 11:12:02 +0700] [54048] [INFO] Waiting for application startup.
[2023-03-07 11:12:02 +0700] [54048] [INFO] Application startup complete.
[2023-03-07 11:12:57 +0700] [54046] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 147, in _connect
    s.connect(resolved_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 284, in connect
    s = BoltSocket._connect(resolved_address, timeout, keep_alive)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 164, in _connect
    raise ServiceUnavailable(
neo4j.exceptions.ServiceUnavailable: Failed to establish connection to ResolvedIPv4Address(('10.242.77.105', 7687)) (reason [Errno 111] Connection refused)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/pusintek/project/dupakq/main.py", line 762, in query_graph2
    result = session.run("match p=(m)-[r]-(n) where toLower(m.label) contains '"+str(x[0]).lower()+"' \
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/work/simple.py", line 204, in run
    self._connect(self._config.default_access_mode)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/work/simple.py", line 108, in _connect
    super()._connect(access_mode)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/work/__init__.py", line 82, in _connect
    self._connection = self._pool.acquire(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 926, in acquire
    return self._acquire(self.address, deadline)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 801, in _acquire
    return connection_creator()
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 729, in connection_creator
    connection = self.opener(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 907, in opener
    return Bolt.open(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 327, in open
    s, pool_config.protocol_version, handshake, data = BoltSocket.connect(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 311, in connect
    raise ServiceUnavailable(
neo4j.exceptions.ServiceUnavailable: Couldn't connect to 10.242.77.105:7687 (resolved to ('10.242.77.105:7687',)):
Failed to establish connection to ResolvedIPv4Address(('10.242.77.105', 7687)) (reason [Errno 111] Connection refused)
[2023-03-07 11:13:02 +0700] [54048] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 147, in _connect
    s.connect(resolved_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 284, in connect
    s = BoltSocket._connect(resolved_address, timeout, keep_alive)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 164, in _connect
    raise ServiceUnavailable(
neo4j.exceptions.ServiceUnavailable: Failed to establish connection to ResolvedIPv4Address(('10.242.77.105', 7687)) (reason [Errno 111] Connection refused)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/pusintek/project/dupakq/main.py", line 762, in query_graph2
    result = session.run("match p=(m)-[r]-(n) where toLower(m.label) contains '"+str(x[0]).lower()+"' \
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/work/simple.py", line 204, in run
    self._connect(self._config.default_access_mode)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/work/simple.py", line 108, in _connect
    super()._connect(access_mode)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/work/__init__.py", line 82, in _connect
    self._connection = self._pool.acquire(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 926, in acquire
    return self._acquire(self.address, deadline)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 801, in _acquire
    return connection_creator()
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 729, in connection_creator
    connection = self.opener(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 907, in opener
    return Bolt.open(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 327, in open
    s, pool_config.protocol_version, handshake, data = BoltSocket.connect(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 311, in connect
    raise ServiceUnavailable(
neo4j.exceptions.ServiceUnavailable: Couldn't connect to 10.242.77.105:7687 (resolved to ('10.242.77.105:7687',)):
Failed to establish connection to ResolvedIPv4Address(('10.242.77.105', 7687)) (reason [Errno 111] Connection refused)
[2023-03-07 11:13:04 +0700] [54050] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 147, in _connect
    s.connect(resolved_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 284, in connect
    s = BoltSocket._connect(resolved_address, timeout, keep_alive)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 164, in _connect
    raise ServiceUnavailable(
neo4j.exceptions.ServiceUnavailable: Failed to establish connection to ResolvedIPv4Address(('10.242.77.105', 7687)) (reason [Errno 111] Connection refused)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/pusintek/project/dupakq/main.py", line 762, in query_graph2
    result = session.run("match p=(m)-[r]-(n) where toLower(m.label) contains '"+str(x[0]).lower()+"' \
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/work/simple.py", line 204, in run
    self._connect(self._config.default_access_mode)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/work/simple.py", line 108, in _connect
    super()._connect(access_mode)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/work/__init__.py", line 82, in _connect
    self._connection = self._pool.acquire(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 926, in acquire
    return self._acquire(self.address, deadline)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 801, in _acquire
    return connection_creator()
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 729, in connection_creator
    connection = self.opener(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 907, in opener
    return Bolt.open(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 327, in open
    s, pool_config.protocol_version, handshake, data = BoltSocket.connect(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 311, in connect
    raise ServiceUnavailable(
neo4j.exceptions.ServiceUnavailable: Couldn't connect to 10.242.77.105:7687 (resolved to ('10.242.77.105:7687',)):
Failed to establish connection to ResolvedIPv4Address(('10.242.77.105', 7687)) (reason [Errno 111] Connection refused)
[2023-03-07 11:13:05 +0700] [54048] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 147, in _connect
    s.connect(resolved_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 284, in connect
    s = BoltSocket._connect(resolved_address, timeout, keep_alive)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 164, in _connect
    raise ServiceUnavailable(
neo4j.exceptions.ServiceUnavailable: Failed to establish connection to ResolvedIPv4Address(('10.242.77.105', 7687)) (reason [Errno 111] Connection refused)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/pusintek/project/dupakq/main.py", line 762, in query_graph2
    result = session.run("match p=(m)-[r]-(n) where toLower(m.label) contains '"+str(x[0]).lower()+"' \
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/work/simple.py", line 204, in run
    self._connect(self._config.default_access_mode)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/work/simple.py", line 108, in _connect
    super()._connect(access_mode)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/work/__init__.py", line 82, in _connect
    self._connection = self._pool.acquire(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 926, in acquire
    return self._acquire(self.address, deadline)
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 801, in _acquire
    return connection_creator()
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 729, in connection_creator
    connection = self.opener(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 907, in opener
    return Bolt.open(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/__init__.py", line 327, in open
    s, pool_config.protocol_version, handshake, data = BoltSocket.connect(
  File "/home/pusintek/miniconda3/envs/py38/lib/python3.8/site-packages/neo4j/io/_socket.py", line 311, in connect
    raise ServiceUnavailable(
neo4j.exceptions.ServiceUnavailable: Couldn't connect to 10.242.77.105:7687 (resolved to ('10.242.77.105:7687',)):
Failed to establish connection to ResolvedIPv4Address(('10.242.77.105', 7687)) (reason [Errno 111] Connection refused)
[2023-03-07 11:14:03 +0700] [57899] [INFO] Starting gunicorn 20.1.0
[2023-03-07 11:14:03 +0700] [57899] [INFO] Listening at: http://10.242.77.105:443 (57899)
[2023-03-07 11:14:03 +0700] [57899] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-03-07 11:14:03 +0700] [57917] [INFO] Booting worker with pid: 57917
[2023-03-07 11:14:03 +0700] [57918] [INFO] Booting worker with pid: 57918
[2023-03-07 11:14:03 +0700] [57919] [INFO] Booting worker with pid: 57919
[2023-03-07 11:14:03 +0700] [57920] [INFO] Booting worker with pid: 57920
[2023-03-07 11:14:08 +0700] [57918] [INFO] Started server process [57918]
[2023-03-07 11:14:08 +0700] [57918] [INFO] Waiting for application startup.
[2023-03-07 11:14:08 +0700] [57918] [INFO] Application startup complete.
[2023-03-07 11:14:08 +0700] [57919] [INFO] Started server process [57919]
[2023-03-07 11:14:08 +0700] [57919] [INFO] Waiting for application startup.
[2023-03-07 11:14:08 +0700] [57919] [INFO] Application startup complete.
[2023-03-07 11:14:08 +0700] [57920] [INFO] Started server process [57920]
[2023-03-07 11:14:08 +0700] [57920] [INFO] Waiting for application startup.
[2023-03-07 11:14:08 +0700] [57920] [INFO] Application startup complete.
[2023-03-07 11:14:08 +0700] [57917] [INFO] Started server process [57917]
[2023-03-07 11:14:08 +0700] [57917] [INFO] Waiting for application startup.
[2023-03-07 11:14:08 +0700] [57917] [INFO] Application startup complete.
[2023-03-07 11:14:41 +0700] [60702] [INFO] Starting gunicorn 20.1.0
[2023-03-07 11:14:41 +0700] [60702] [INFO] Listening at: http://10.242.77.105:443 (60702)
[2023-03-07 11:14:41 +0700] [60702] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-03-07 11:14:41 +0700] [60717] [INFO] Booting worker with pid: 60717
[2023-03-07 11:14:41 +0700] [60718] [INFO] Booting worker with pid: 60718
[2023-03-07 11:14:41 +0700] [60719] [INFO] Booting worker with pid: 60719
[2023-03-07 11:14:41 +0700] [60720] [INFO] Booting worker with pid: 60720
[2023-03-07 11:14:46 +0700] [60717] [INFO] Started server process [60717]
[2023-03-07 11:14:46 +0700] [60717] [INFO] Waiting for application startup.
[2023-03-07 11:14:46 +0700] [60717] [INFO] Application startup complete.
[2023-03-07 11:14:46 +0700] [60720] [INFO] Started server process [60720]
[2023-03-07 11:14:46 +0700] [60720] [INFO] Waiting for application startup.
[2023-03-07 11:14:46 +0700] [60720] [INFO] Application startup complete.
[2023-03-07 11:14:46 +0700] [60719] [INFO] Started server process [60719]
[2023-03-07 11:14:46 +0700] [60719] [INFO] Waiting for application startup.
[2023-03-07 11:14:46 +0700] [60719] [INFO] Application startup complete.
[2023-03-07 11:14:46 +0700] [60718] [INFO] Started server process [60718]
[2023-03-07 11:14:46 +0700] [60718] [INFO] Waiting for application startup.
[2023-03-07 11:14:46 +0700] [60718] [INFO] Application startup complete.
[2023-03-07 11:16:40 +0700] [65095] [INFO] Starting gunicorn 20.1.0
[2023-03-07 11:16:40 +0700] [65095] [INFO] Listening at: http://10.242.77.105:443 (65095)
[2023-03-07 11:16:40 +0700] [65095] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-03-07 11:16:40 +0700] [65121] [INFO] Booting worker with pid: 65121
[2023-03-07 11:16:40 +0700] [65122] [INFO] Booting worker with pid: 65122
[2023-03-07 11:16:40 +0700] [65123] [INFO] Booting worker with pid: 65123
[2023-03-07 11:16:41 +0700] [65124] [INFO] Booting worker with pid: 65124
[2023-03-07 11:16:45 +0700] [65122] [INFO] Started server process [65122]
[2023-03-07 11:16:45 +0700] [65122] [INFO] Waiting for application startup.
[2023-03-07 11:16:45 +0700] [65122] [INFO] Application startup complete.
[2023-03-07 11:16:45 +0700] [65123] [INFO] Started server process [65123]
[2023-03-07 11:16:45 +0700] [65123] [INFO] Waiting for application startup.
[2023-03-07 11:16:45 +0700] [65123] [INFO] Application startup complete.
[2023-03-07 11:16:45 +0700] [65121] [INFO] Started server process [65121]
[2023-03-07 11:16:45 +0700] [65121] [INFO] Waiting for application startup.
[2023-03-07 11:16:45 +0700] [65121] [INFO] Application startup complete.
[2023-03-07 11:16:45 +0700] [65124] [INFO] Started server process [65124]
[2023-03-07 11:16:45 +0700] [65124] [INFO] Waiting for application startup.
[2023-03-07 11:16:45 +0700] [65124] [INFO] Application startup complete.
[2023-03-07 11:22:09 +0700] [73234] [INFO] Starting gunicorn 20.1.0
[2023-03-07 11:22:09 +0700] [73234] [INFO] Listening at: http://10.242.77.105:443 (73234)
[2023-03-07 11:22:09 +0700] [73234] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-03-07 11:22:09 +0700] [73249] [INFO] Booting worker with pid: 73249
[2023-03-07 11:22:09 +0700] [73250] [INFO] Booting worker with pid: 73250
[2023-03-07 11:22:09 +0700] [73251] [INFO] Booting worker with pid: 73251
[2023-03-07 11:22:09 +0700] [73252] [INFO] Booting worker with pid: 73252
[2023-03-07 11:22:14 +0700] [73250] [INFO] Started server process [73250]
[2023-03-07 11:22:14 +0700] [73250] [INFO] Waiting for application startup.
[2023-03-07 11:22:14 +0700] [73250] [INFO] Application startup complete.
[2023-03-07 11:22:15 +0700] [73249] [INFO] Started server process [73249]
[2023-03-07 11:22:15 +0700] [73249] [INFO] Waiting for application startup.
[2023-03-07 11:22:15 +0700] [73249] [INFO] Application startup complete.
[2023-03-07 11:22:15 +0700] [73251] [INFO] Started server process [73251]
[2023-03-07 11:22:15 +0700] [73251] [INFO] Waiting for application startup.
[2023-03-07 11:22:15 +0700] [73251] [INFO] Application startup complete.
[2023-03-07 11:22:15 +0700] [73252] [INFO] Started server process [73252]
[2023-03-07 11:22:15 +0700] [73252] [INFO] Waiting for application startup.
[2023-03-07 11:22:15 +0700] [73252] [INFO] Application startup complete.
